name: flutterlocation
repository: https://github.com/Lyokone/flutterlocation
packages:
  - packages/**

scripts:
  check:
    run: |
      melos run analyze
      melos run format:dry-run
      melos run test
      melos run pub:dry-run
    description: Run all static analysis checks.

  analyze:
    run: melos exec -- \
      dart analyze . --fatal-infos
    description: Run `dart analyze` in all packages.
  format:
    run: melos exec -- \
      dart format .
    description: Run `dart format` in all packages.
  format:dry-run:
    run: melos exec -- \
      dart format . --set-exit-if-changed
    description: Run `dart format` in all packages, but don't make any changes.

  pub:dry-run:
    run: melos exec -- \
      dart pub publish --dry-run
    description: Run `dart pub publish` in all packages in dry run mode.
    packageFilters:
      ignore:
        - 'example'

  test:all:
    run: melos run test --no-select
    description: Run all tests available on stable channel

  test:
    run: |
      melos exec -- \
        "flutter test --no-pub --coverage"
    description: Run `flutter test` for a specific package.
    packageFilters:
      dirExists:
        - test
