name: location_platform_interface
description: A common platform interface for the location plugin.
version: 3.0.0
homepage: https://github.com/Lyokone/flutterlocation

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  leancode_lint: ^3.0.0
  mockito: ^5.0.0
