name: location_example
description: Demonstrates how to use the location plugin.

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  location:
    path: ../
  url_launcher: ^6.0.2

flutter:
  uses-material-design: true
