name: location
description: Cross-platform plugin for easy access to device's location in real-time.
version: 5.0.0
homepage: https://docs.page/Lyokone/flutterlocation
repository: https://github.com/Lyokone/flutterlocation
issue_tracker: https://github.com/Lyokone/flutterlocation/issues

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

flutter:
  plugin:
    platforms:
      android:
        package: com.lyokone.location
        pluginClass: LocationPlugin
      ios:
        pluginClass: LocationPlugin
      macos:
        pluginClass: LocationPlugin
      web:
        default_package: location_web

dependencies:
  flutter:
    sdk: flutter
  location_platform_interface: ^3.0.0
  location_web: ^3.1.1
dev_dependencies:
  async: ^2.5.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mockito: ^5.0.0
