name: location_platform_interface
description: A common platform interface for the location plugin.
version: 0.0.1

environment:
  sdk: ">=2.4.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  plugin_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
